services:
  app:
    container_name: prisma-orm-leak-app
    build: .
    environment:
      - 'DATABASE_URL=postgresql://psuser:securepassword@postgres:5432/blog'
    depends_on:
      - postgres
    ports:
      - '9900:9999'

  postgres:
    container_name: prisma-orm-leak-postgres
    image: postgres:12
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=psuser
      - POSTGRES_PASSWORD=securepassword
    ports:
      - '5432:5432'
